# Development-only Hibernate logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allows IntelliJ to inspect Actuator endpoints during development
management.endpoints.jmx.exposure.include=*

# Longer access token lifetime for local development
jwt.expiry-in-seconds=${JWT_EXPIRY_SECONDS:604800}