CREATE TABLE shopping_cart (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               user_id BIGINT NOT NULL,
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT pk_shopping_cart
                                   PRIMARY KEY (id),

                               CONSTRAINT uk_shopping_cart_user
                                   UNIQUE (user_id),

                               CONSTRAINT fk_shopping_cart_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES local_user (id)
                                       ON DELETE CASCADE
);

CREATE TABLE shopping_cart_item (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    cart_id BIGINT NOT NULL,
                                    product_id BIGINT NOT NULL,
                                    quantity INTEGER NOT NULL,
                                    version BIGINT NOT NULL DEFAULT 0,

                                    CONSTRAINT pk_shopping_cart_item
                                        PRIMARY KEY (id),

                                    CONSTRAINT uk_shopping_cart_item_cart_product
                                        UNIQUE (cart_id, product_id),

                                    CONSTRAINT chk_shopping_cart_item_quantity
                                        CHECK (quantity > 0),

                                    CONSTRAINT fk_shopping_cart_item_cart
                                        FOREIGN KEY (cart_id)
                                            REFERENCES shopping_cart (id)
                                            ON DELETE CASCADE,

                                    CONSTRAINT fk_shopping_cart_item_product
                                        FOREIGN KEY (product_id)
                                            REFERENCES product (id)
);

CREATE INDEX idx_shopping_cart_item_product
    ON shopping_cart_item (product_id);