CREATE TABLE refresh_session (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 session_id VARCHAR(36) NOT NULL,
                                 user_id BIGINT NOT NULL,
                                 token_version BIGINT NOT NULL DEFAULT 0,
                                 revoked BOOLEAN NOT NULL DEFAULT FALSE,
                                 created_at TIMESTAMP NOT NULL,
                                 expires_at TIMESTAMP NOT NULL,

                                 CONSTRAINT uk_refresh_session_session_id
                                     UNIQUE (session_id),

                                 CONSTRAINT fk_refresh_session_user
                                     FOREIGN KEY (user_id)
                                         REFERENCES local_user (id)
                                         ON DELETE CASCADE
);

CREATE INDEX idx_refresh_session_user_id
    ON refresh_session (user_id);