--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    country character varying(75) NOT NULL,
    address_line_1 character varying(512) NOT NULL,
    address_line_2 character varying(512),
    city character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: local_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.local_user (
    id bigint NOT NULL,
    email character varying(320) NOT NULL,
    email_verified boolean NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(1000) NOT NULL,
    username character varying(255) NOT NULL,
    role character varying(255)
);


--
-- Name: local_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.local_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.local_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    long_description character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    short_description character varying(255) NOT NULL,
    active boolean
);


--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_order_quantity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_order_quantity (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: product_order_quantity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_order_quantity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_order_quantity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    comment character varying(255),
    created_at timestamp(6) without time zone,
    rating integer,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_token (
    id bigint NOT NULL,
    created_timestamp timestamp(6) without time zone NOT NULL,
    token character varying(2048) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: verification_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: web_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.web_order (
    id bigint NOT NULL,
    address_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255),
    CONSTRAINT web_order_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: web_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.web_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- Name: local_user local_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_user
    ADD CONSTRAINT local_user_pkey PRIMARY KEY (id);


--
-- Name: product_order_quantity product_order_quantity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_order_quantity
    ADD CONSTRAINT product_order_quantity_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: stock stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (id);


--
-- Name: local_user uk46f7ufu7j9nkhuyfly98to4u1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_user
    ADD CONSTRAINT uk46f7ufu7j9nkhuyfly98to4u1 UNIQUE (email);


--
-- Name: local_user uk93d93k106ik2383youkc9bixl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.local_user
    ADD CONSTRAINT uk93d93k106ik2383youkc9bixl UNIQUE (username);


--
-- Name: product ukjmivyxk9rmgysrmsqw15lqr5b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT ukjmivyxk9rmgysrmsqw15lqr5b UNIQUE (name);


--
-- Name: stock ukkhabtqwr86p7x9mt2krib98tx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT ukkhabtqwr86p7x9mt2krib98tx UNIQUE (product_id);


--
-- Name: verification_token ukp678btf3r9yu6u8aevyb4ff0m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT ukp678btf3r9yu6u8aevyb4ff0m UNIQUE (token);


--
-- Name: verification_token verification_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT verification_token_pkey PRIMARY KEY (id);


--
-- Name: web_order web_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_order
    ADD CONSTRAINT web_order_pkey PRIMARY KEY (id);


--
-- Name: web_order fk65jlvhv84w95l6dimcc1p6hqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_order
    ADD CONSTRAINT fk65jlvhv84w95l6dimcc1p6hqr FOREIGN KEY (address_id) REFERENCES public.address(id);


--
-- Name: product_order_quantity fk7ckcjpc8rkn1ct52emclbsjep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_order_quantity
    ADD CONSTRAINT fk7ckcjpc8rkn1ct52emclbsjep FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: web_order fk8mvneqqd44higf18x0m67bg29; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_order
    ADD CONSTRAINT fk8mvneqqd44higf18x0m67bg29 FOREIGN KEY (user_id) REFERENCES public.local_user(id);


--
-- Name: verification_token fk8tx2aau9yc0gsxb82192wkyyl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT fk8tx2aau9yc0gsxb82192wkyyl FOREIGN KEY (user_id) REFERENCES public.local_user(id);


--
-- Name: product_order_quantity fke0p6a41oep5jl58aut416wxs5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_order_quantity
    ADD CONSTRAINT fke0p6a41oep5jl58aut416wxs5 FOREIGN KEY (order_id) REFERENCES public.web_order(id);


--
-- Name: review fkh7lu7ggmsawn8big7homihw9m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkh7lu7ggmsawn8big7homihw9m FOREIGN KEY (user_id) REFERENCES public.local_user(id);


--
-- Name: review fkiyof1sindb9qiqr9o8npj8klt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkiyof1sindb9qiqr9o8npj8klt FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: stock fkjghkvw2snnsr5gpct0of7xfcf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT fkjghkvw2snnsr5gpct0of7xfcf FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: address fkkb7b5aavt0mlydpvdiuesa9r8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT fkkb7b5aavt0mlydpvdiuesa9r8 FOREIGN KEY (user_id) REFERENCES public.local_user(id);


--
-- PostgreSQL database dump complete
--


